const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const c={characterId:0,chatId:'voices',name1:'Ариша',name2:'Леон',characters:[{description:'Леон сдержанный.',mes_example:'<START>\n{{char}}: '+ 'Речь. '.repeat(500)+'CHAR_VOICE_END: отвечаю кратко.' ,data:{extensions:{world:'people'},character_book:{entries:[{keys:['Марвин Бранаг'],content:'EMBEDDED_NPC_VOICE: вежливый, полные фразы.'},{keys:['Марвин Бранаг'],content:'DISABLED_EMBEDDED',enabled:false}]}}}],chat:[{name:'Леон',mes:'Леон ушёл на работу.'},{name:'Ариша',mes:'Я осталась дома.',is_user:true}],chatMetadata:{},extensionSettings:{cityhub:{}},setExtensionPrompt(){},loadWorldInfo:async()=>({entries:{marvin:{key:['Marvin Branagh'],content:'Марвин Бранаг: '+ 'Биография. '.repeat(600)+'NPC_VOICE_END: официальные обращения; без эмодзи и сленга.'},other:{key:['Леонид'],content:'UNRELATED_LEONID_VOICE'},disabled:{key:['Marvin Branagh'],content:'DISABLED_NPC_VOICE',disable:true}}})};
const env={console,Date,Math,JSON,Promise,Map,Set,WeakMap,WeakSet,SillyTavern:{getContext:()=>c},window:{addEventListener(){}},document:{getElementById:()=>null},jQuery(){},toastr:{info(){},success(){},warning(){},error(){}},setTimeout(){},clearTimeout(){},setInterval(){}};
vm.createContext(env);const source=fs.readFileSync(path.join(__dirname,'..','index.js'),'utf8').replace('    globalThis.CityHub = {',`globalThis.test={voiceContext,aiComments,charCommentRule,ACT,reply,model:fn=>aiRaw=fn};save=()=>{};render=()=>{};globalThis.CityHub = {`);
vm.runInContext(source,env);const api=env.test,s=env.CityHub.state();s.auth=true;
s.lorePeople=[{name:'Марвин Бранаг',aliases:['Marvin Branagh'],role:'adult',bio:'Коллега; сдержанный.'}];
s.threads=[{id:'npc',name:'Марвин Бранаг',kind:'dm',bio:'Всегда вежлив.',msgs:[{text:'PRIVATE_DM_SECRET',me:false,t:1}],rel:20},{id:'char',name:'Леон',kind:'char',pair:true,rel:70,msgs:[]}];
const p={id:'post',author:'Марвин Бранаг',text:'PUBLIC_STYLE_SAMPLE',comments:[{id:'cmt',author:'Марвин Бранаг',text:'PUBLIC_REPLY_STYLE',t:1}],t:1};s.feed=[p];
function check(prompt){for(const marker of ['CHAR_VOICE_END','NPC_VOICE_END','EMBEDDED_NPC_VOICE','PUBLIC_STYLE_SAMPLE','PUBLIC_REPLY_STYLE','Не переноси голос основного персонажа на NPC','Эмодзи и сленг используй только если'])assert.ok(prompt.includes(marker),marker);for(const marker of ['PRIVATE_DM_SECRET','DISABLED_EMBEDDED','DISABLED_NPC_VOICE','UNRELATED_LEONID_VOICE','коротко, эмоционально, с эмодзи и сленгом'])assert.ok(!prompt.includes(marker),marker);}
(async()=>{
 check(await api.voiceContext(s,['Marvin Branagh']));
 let prompt;
 api.model(async p=>{prompt=p;return '[{"author":"Марвин Бранаг","text":"Добрый день.","replyTo":"Ариша"}]';});
 const comments=await api.aiComments(s,p,'Ответь Арише в ветке.');check(prompt);assert.equal(comments[0].author,'Марвин Бранаг');assert.ok(prompt.includes('Леон ушёл на работу.'));assert.ok(!api.charCommentRule(s).includes('близкий или влюблённый поддержит'));
 api.model(async p=>{prompt=p;return '{"posts":[{"author":"Марвин Бранаг","text":"Добрый день.","channel":"general"}],"stories":[]}';});await api.ACT.genFeed({},null,s);check(prompt);assert.ok(s.feed.some(p=>p.text==='Добрый день.'));
 api.model(async p=>p.startsWith('Проверка текущей сцены')?'{"state":"apart","evidence":""}':(prompt=p,'{"reply":"Добрый день.","delta":0}'));assert.equal(await api.reply(s,s.threads[0]),'delivered');assert.ok(prompt.includes('NPC_VOICE_END'));assert.ok(prompt.includes('EMBEDDED_NPC_VOICE'));assert.ok(prompt.includes('Эмодзи и сленг используй только если'));assert.ok(!prompt.includes('CHAR_VOICE_END'),'NPC does not receive char speech examples');
 // A voice source loaded for the old chat must not trigger generation in the new chat.
 let release,started,calls=0;const ready=new Promise(r=>started=r);c.loadWorldInfo=()=>{started();return new Promise(r=>release=r);};api.model(async()=>{calls++;return '[]';});const pending=api.aiComments(s,p,'Ответь.');await ready;c.chatId='new';c.chatMetadata={};release({entries:{}});await pending;assert.equal(calls,0);
 console.log('PASS: full char speech examples and NPC lore in feed/comment requests; aliases; disabled/unrelated source isolation; public style without DM leaks; individual tones; NPC DM sources; stale-chat guard');
})().catch(e=>{console.error(e);process.exitCode=1;});
